# Generated by Django 3.1.2 on 2020-10-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('audio_rate', models.IntegerField(blank=True, null=True)),
                ('volume_level', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('audio_voice', models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=1, max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
